service: qr-with-text-go
frameworkVersion: ">=3.7.5"

provider:
  name: aws
  runtime: go1.x
  region: ap-northeast-1
  profile: ${opt:profile, self:custom.dummyDataToFail}
  stage: ${opt:stage, self:custom.dummyDataToFail}
  environment:
    TZ: Asia/Tokyo

plugins:
  - serverless-apigw-binary
custom:
  dummyDataToFail: dummy_data_to_fail
  bucket: qr-generator-v2-${self:provider.stage}
  apigwBinary:
    types:
      - "image/png"
      - "*/*"

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  qr_with_text_go:
    handler: bin/main
    description: Managed by qr-with-text-go in serverless
    timeout: 5
    events:
      - http:
          path: qr-png
          method: get
          contentHandling: CONVERT_TO_BINARY

resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}
  Outputs:
    ApiDistribution:
      Description: "ApiDistribution"
      Value: ApiDistribution
